# Stage 1: Build Angular frontend
FROM node:lts-alpine AS frontend-build

WORKDIR /mean-app

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .
RUN yarn build --prod

# Stage 2: Build Node.js backend
FROM node:alpine

WORKDIR /mean-app

ENV HUSKY_SKIP_INSTALL=1
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --production

COPY . .

COPY --from=frontend-build /mean-app/dist ./dist

EXPOSE 3000

CMD ["node", "server.js"]